# This workflow will generate modular docs and publish to the modular-docs branch

name: Modular docs publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Source
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - run: make generate-modular-docs
        name: Generate modular-docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: modular-docs # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
