# This workflow will generate modular docs and publish to the modular-docs branch

name: Downstream docs publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Source
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - run: make generate-downstream-docs
        name: Generate generate-downstream-docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: downstream-docs # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
